# github action to deploy munsonpickles web to azure

name: Deploy MunsonPickles Web

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore munsonpickles.sln
      - name: Build
        run: dotnet build munsonpickles.sln --configuration Release --no-restore


   