# github action to deploy munsonpickles web to azure

name: Deploy MunsonPickles Web

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "app-munson-web-eastus-dev-001"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore ./MunsonPickles.Web/MunsonPickles.Web.csproj
      - name: Build
        run: dotnet build ./MunsonPickles.Web/MunsonPickles.Web.csproj --configuration Release --no-restore

      # publish
      - name: publish
        run: dotnet publish ./MunsonPickles.Web/MunsonPickles.Web.csproj --configuration Release --output ./publish

      # deploy to azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.WEB_PUBLISH_SECRET}}
          package: ./publish